# Emart Online Shopping - Assignment
Deadline: October 04, 11 AM. Send it to my email.

We have created a fabricated data about some purchases done via Emart Online Shopping! You are required to do the tasks.Usually your answer is just one line of code. Make sure to have have the attached 'Emart Online Shopping'dataset!

In [1]:
#Q1: Run pandas lib
import pandas as pd

In [3]:
#Q2: Read the attached CSV dataset 'Emart Online Shopping'
emart = pd.read_csv("C:/Users/oguru/Downloads/Emart Online Shopping")

In [5]:
#Q3: Display head of the'Emart Online Shopping' dataset 
emart.describe()
emart.head()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [10]:
# Q4. check number of rows and columns
emart.shape

(10000, 14)

In [11]:
#Q5: Calculate average of the Purchase?
purchase= emart.groupby('Purchase Price')
purchase.mean()

                 Credit Card  CC Security Code
Purchase Price
0.00            2.117485e+15             137.0
0.01            4.759624e+15             600.0
0.02            2.530742e+15             541.5
0.03            9.036526e+13             376.0
0.04            3.728702e+14             940.0
...                      ...               ...
99.92           1.072146e+14             610.0
99.93           3.088953e+15             493.0
99.95           5.038704e+11             312.0
99.97           6.011037e+15             757.0
99.99           1.720107e+13             871.0

[6349 rows x 2 columns]

In [12]:
#Q6. find the highest purchase
purchase.max()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language
Purchase Price,,,,,,,,,,,,,
0.00,"465 Mallory Ways\nNorth Rebecca, RI 82734-1160",93 OH,PM,Mozilla/5.0 (X11; Linux i686; rv:1.9.6.20) Gec...,"Lyons, Diaz and Clark",4204500444841766,09/23,236,VISA 16 digit,mjohnson@austin.org,Stage manager,43.99.56.59,zh
0.01,"9202 Baker Forks\nNew Chelseaborough, VA 70852",40 Vx,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sanchez-Stephenson,4759624285678506,08/18,600,VISA 16 digit,leesabrina@rojas.com,Television camera operator,143.139.184.18,es
0.02,"402 Joseph Tunnel Apt. 219\nMartinmouth, DE 58480",95 xb,PM,Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_7...,Wagner Group,4720459683484280,08/21,866,Mastercard,rramsey@oliver.com,Product/process development scientist,69.92.84.253,ru
0.03,Unit 9279 Box 5039\nDPO AP 86638,69 MM,PM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_0...,Washington-Johnson,180054117657378,07/25,448,Voyager,kimberlyolsen@hotmail.com,"Research officer, government",207.65.121.44,el
0.04,"827 Kathryn Rest Suite 059\nGouldside, PA 4949...",04 ER,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Murphy-Gardner,372870195456666,04/26,940,Diners Club / Carte Blanche,qcross@james.org,"Surveyor, mining",229.94.185.56,ru
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99.92,"PSC 1273, Box 3037\nAPO AA 11854-3422",93 HJ,PM,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Fisher-Guerrero,210065564716644,08/22,628,Voyager,vegaallen@gmail.com,Tree surgeon,158.196.81.143,it
99.93,"27148 Kathy Cliff Apt. 400\nEast Jillton, TX 5...",37 ou,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,King and Sons,3088952915231147,04/17,493,Mastercard,lpowell@yahoo.com,Television camera operator,110.244.150.130,el
99.95,"672 James Oval\nNew Davidview, KS 91202",07 dT,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90; it-IT; r...,Fitzpatrick Group,503870406017,05/24,312,JCB 15 digit,mjenkins@gmail.com,"Teacher, primary school",192.227.38.104,el
99.97,"058 Miranda Locks Suite 792\nPort Davidstad, P...",73 IW,PM,Mozilla/5.0 (Windows NT 5.0) AppleWebKit/5360 ...,Olson-Navarro,6011037226242937,03/18,757,American Express,brendastewart@dalton.info,Site engineer,96.79.250.154,de
99.99,"PSC 6177, Box 1004\nAPO AA 57143-1269",64 Nf,AM,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,"Porter, Johnson and Pratt",30109394842259,11/25,918,VISA 16 digit,kelli72@gmail.com,"Surveyor, insurance",89.51.92.242,el

In [13]:
#Q7. find the lowest purchase
purchase.min()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language
Purchase Price,,,,,,,,,,,,,
0.00,"332 Jones Parkways\nEast Katherineville, GA 64230",39 GT,AM,Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_9...,Flynn and Sons,30469912089738,01/18,38,Discover,jennifer11@baker.com,Biomedical scientist,223.47.177.174,it
0.01,"9202 Baker Forks\nNew Chelseaborough, VA 70852",40 Vx,AM,Mozilla/5.0 (iPod; U; CPU iPhone OS 3_3 like M...,Sanchez-Stephenson,4759624285678506,08/18,600,VISA 16 digit,leesabrina@rojas.com,Television camera operator,143.139.184.18,es
0.02,"146 Laura Mission\nNorth Donald, NC 76608",46 Yg,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_2 ...,Armstrong PLC,341024981858937,06/19,217,Discover,emilypotter@yahoo.com,IT trainer,66.97.84.200,de
0.03,"86103 Ricky Manor\nNunezton, VI 03206-5280",40 Ai,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_1;...,Roberts LLC,676398186905,01/25,304,Voyager,heatherpham@hotmail.com,"Civil engineer, contracting",118.191.31.116,de
0.04,"827 Kathryn Rest Suite 059\nGouldside, PA 4949...",04 ER,PM,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Murphy-Gardner,372870195456666,04/26,940,Diners Club / Carte Blanche,qcross@james.org,"Surveyor, mining",229.94.185.56,ru
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99.92,"408 Russell Club\nSouth Thomas, MT 73554-8846",82 iO,AM,Mozilla/5.0 (compatible; MSIE 6.0; Windows 95;...,Bond-Oconnor,4363719050674,04/24,592,Mastercard,david10@dodson-warner.com,Careers adviser,111.5.222.164,fr
99.93,"27148 Kathy Cliff Apt. 400\nEast Jillton, TX 5...",37 ou,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,King and Sons,3088952915231147,04/17,493,Mastercard,lpowell@yahoo.com,Television camera operator,110.244.150.130,el
99.95,"672 James Oval\nNew Davidview, KS 91202",07 dT,PM,Mozilla/5.0 (Windows 98; Win 9x 4.90; it-IT; r...,Fitzpatrick Group,503870406017,05/24,312,JCB 15 digit,mjenkins@gmail.com,"Teacher, primary school",192.227.38.104,el
99.97,"058 Miranda Locks Suite 792\nPort Davidstad, P...",73 IW,PM,Mozilla/5.0 (Windows NT 5.0) AppleWebKit/5360 ...,Olson-Navarro,6011037226242937,03/18,757,American Express,brendastewart@dalton.info,Site engineer,96.79.250.154,de
99.99,"63773 Shelton Greens\nAshleyton, MA 00493",56 lu,AM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_4)...,Pitts Group,4292741269160,06/18,824,Maestro,heatherwoodard@lloyd.com,"Surveyor, hydrographic",172.197.216.229,de

In [36]:
#Q8. Find number of people who used English language 'en' on the Emart Shopping website

(emart["Language"]=='en').sum()

1098

In [29]:
#Q9. Count how many people have their job title as "engineer" ?
by_title = emart.groupby('Job')
by_title.Job.value_counts()

Job                               Job
Academic librarian                Academic librarian                  11
Accommodation manager             Accommodation manager               17
Accountant, chartered             Accountant, chartered               20
Accountant, chartered certified   Accountant, chartered certified     18
Accountant, chartered management  Accountant, chartered management    15
                                                                      ..
Water quality scientist           Water quality scientist             18
Web designer                      Web designer                        20
Wellsite geologist                Wellsite geologist                  24
Writer                            Writer                              10
Youth worker                      Youth worker                        18
Name: Job, Length: 623, dtype: int64

In [43]:
#Q10. Count people who purchase during the AM and PM ? 
x= emart['AM'].str.count('AM')

KeyError: 'AM'

In [37]:
#Q11. find out the 3 most common Job Titles
emart['Job'].value_counts().nlargest(3)

Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Name: Job, dtype: int64

In [38]:
#Q12. Find out number of Mastercard holders who purchased over $86
emart['Purchase Price'].gt(86).sum()

1466

In [40]:
#Q13.Find out the top 3 email providers

series= emart['Email'].str.split(pat="@",n=1,expand=True)
emart['Email Provider']=series[1]
emart['Email Provider'].value_counts().nlargest(3)

hotmail.com    1638
yahoo.com      1616
gmail.com      1605
Name: Email Provider, dtype: int64

# Please make sure to have your own solution!